#!/bin/bash
N="1e4"
alg="single,cluster"
./sigmaModel -cool 4,0,10 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,20 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,30 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,40 -c "$N" -alg "$alg" 
alg="random,metropolis"
./sigmaModel -cool 4,0,10 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,20 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,30 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,40 -c "$N" -alg "$alg" 
alg="random,glauber"
./sigmaModel -cool 4,0,10 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,20 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,30 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,40 -c "$N" -alg "$alg" 
alg="lexic,metropolis"
./sigmaModel -cool 4,0,10 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,20 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,30 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,40 -c "$N" -alg "$alg" 
alg="lexic,glauber"
./sigmaModel -cool 4,0,10 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,20 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,30 -c "$N" -alg "$alg" 
./sigmaModel -cool 4,0,40 -c "$N" -alg "$alg" 