#!/bin/python3

import os, argparse
parser = argparse.ArgumentParser()
parser.add_argument('-co','--cooling', type=str, default="4:0")
parser.add_argument('-st','--step', type=str, default='metropolis')
parser.add_argument('-n','--statistics', type=float, default=1000)
parser.add_argument('-tq','--spacing', type=NotImplementedError, default=10)

args = parser.parse_args()

# performance

cmd_compile = ["gfortran", "-ofast", 
               "-floop-parallelize-all",
               "-o", "output/main m_progress_bar.f90", 
                "functions.f90", "algorithm.f90"]
if len(args.cooling)>2:
    cmd_compile.append('cooling.f90')
    rangeTemp = args.cooling.split(':')
    cmd_run = ["./output/main", args.step, f"{args.spacing}" ,
                f"{int(args.statistics)}", f"{rangeTemp[0]}", f"{rangeTemp[1]}"]

# debug
# gfortran -g -O0 -Wall -o output/main m_progress_bar.f90 functions.f90 algorithm.f90 main.f90

os.system(" ".join(cmd_compile))
os.system(" ".join(cmd_run))
